### PR TITLE
added standard c# .gitignore/.gitattributes configuration and removed files that should be excluded

### PR DESCRIPTION
**Pull request by ghuntley**
@robfry thanks for your contribution to the OSS community and congratulations on your first public project. Please ignore #2 and if you ever need help with .NET then hit me up :sparkling_heart:

### CODE REVIEW

**Comment by b** [comment]
keep it classy, @ghuntley

**Comment by cottsak** [comment]
stay classy @b

**Comment by shiftkey** [comment]
Hey @ghuntley while you're in here there's a bit more cleanup I'd recommend for the project file:

- tracked files under `bin\` - https://github.com/Netflix/Fido/blob/master/FIDO.csproj#L240 and https://github.com/Netflix/Fido/blob/master/FIDO.csproj#L265-L329
- `Service References` and `Web References` are not necessary for this - https://github.com/Netflix/Fido/blob/master/FIDO.csproj#L265-L329

**Comment by robfry** [comment]
@ghuntley Thanks for the offer, I'll take you up on it. :) 

@shiftkey @ghuntley Thanks for the updates, I'll get this merged soon.

**Comment by ghuntley** [comment]
imgoingin

modifications as suggested by @shiftkey applied.

**Comment by DaveLundie** [comment]
Hi There, I am new to this site and project so please excuse if I post this comment at the wrong place. where can I get the x64 Windows installer mentioned in this link https://github.com/Netflix/Fido/wiki/Windows-Setup
Much appreciated . I am an Info Sec specialist and would most likely like to get involved here by contributing as a few things i read here was things I considered building and actually have done a few but why re invent the wheel completely :-)

**Comment by shiftkey** [comment]
@DaveLundie I recommend opening a new issue to discuss this - I had a quick look but couldn't find anything obvious.

**Comment by DaveLundie** [comment]
Thank you @shiftkey , i found a topic around this created 7 May but no resolution to the availability of the installer. I will keep on looking. Appreciate the help :-)

**Comment by harryxy12345** [comment]
SORRY I CAN'T GIVE YOU AN ANSWER.
Am 22.08.2015 02:42 schrieb "Brendan Forster" <notifications@github.com>:

**Pull request merged**
